# Generated by Django 3.1 on 2020-09-17 08:56

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('deadline', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('status', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='accounts.project')),
            ],
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shotcode', models.CharField(max_length=60, unique=True)),
                ('status', models.CharField(max_length=60)),
                ('cut_in', models.DecimalField(decimal_places=2, max_digits=9)),
                ('cut_out', models.DecimalField(decimal_places=2, max_digits=9)),
                ('cut_duration', models.DecimalField(decimal_places=2, max_digits=9)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='accounts.sequence')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.ForeignKey(default=accounts.models.get_default_artist_usertype, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.usertype'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=60, unique=True)),
                ('pipeline_step', models.CharField(max_length=60)),
                ('status', models.CharField(max_length=60)),
                ('startdate', models.DateField()),
                ('duedate', models.DateField()),
                ('assigned_to', models.ManyToManyField(related_name='assignedtasks', to=settings.AUTH_USER_MODEL)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='accounts.shot')),
                ('reviewer', models.ManyToManyField(related_name='taskstoreview', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
